# package
package(default_visibility = ["//visibility:public"])

load("@pip//:requirements.bzl", "requirement")

py_library(
	name = "GodlikeRoll",
	srcs = ["GodlikeRoll.py"],
	deps = [],
)

py_library(
	name = "Macros",
	srcs = ["Macros.py"],
	deps = [],
)
